<h1><?php echo $this->pageTitle; ?></h1>
<?php echo $this->form; ?>

<div id="modal-ver" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Imagem</h3>
    </div>
    <div class="modal-body">
        <img src="" alt="" title="" style="width:530px;height:400px;" />
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-primary" data-dismiss="modal">Fechar</a>
    </div>
</div>

<script type="text/javascript" src="js/jquery.template.js"></script>
<script type="text/javascript">
    $(function() {
        $('#data').setMask({
            mask : '39/19/9999',
            autoTab : false
        });
        $('#data').datepicker();

        $('form').magicform({
            onOkForwardTo : '<?php echo $this->backUrl; ?>',
            onFieldError : function(key, error) {
                if(key == 'ativo') {
                    $('#ativo-container').append('<span class="help-inline" style="float:right;">' + error + '</span>');
                    return false;
                }
                return true;
            }
        });

        $('#imagem_atual').click(function() {
            $('#modal-ver .modal-body img').attr('src', this.href);
        });

        $('.has_tooltip').tooltip();
    });
</script>