<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="./"><?php echo Lib_Config_Ini::instance()->appname; ?></a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="dropdown">
                        <a href="./"><i class="icon-white icon-home"></i> Home</a>
                    </li>
                    <li class="dropdown">
                        <a href="trabalhe-conosco"><i class="icon-white icon-edit"></i> Trabalhe conosco</a>
                    </li>
                    <li class="dropdown">
                        <a href="login">Login</a>
                    </li>
                </ul>
                <ul class="nav pull-right">
                    <li>
                        <a href="logout">Sair</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>