<div class="bloco_rodape">
    <ul class="rodape">
        <li><a href="a-empresa.htm" title="A Empresa">A Empresa</a></li>
        <li><a href="servicos.htm" title="Servi&ccedil;os">Serviços</a></li>
        <li><a href="clientes.htm" title="Clientes">Clientes</a></li>
        <li><a href="trabalhe-conosco.htm" title="Trabalhe Conosco">Trabalhe Conosco</a></li>
        <li><a href="contato.htm" title="Contato">Contato</a></li>
        <li><a href="news-agf.htm" title="News AGF">News AGF</a> </li>
        <li><a href="index.htm" title="Home">Home</a></li>
    </ul>
</div>