<div class="topo">
    <div class="menu_internas">
        <script type="text/javascript">AC_FL_RunContent( 'codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cabjavascript:void(0)version=9,0,28,0','width','970','height','240','src','swf/interna','movie','swf/interna','quality','high','pluginspage','http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash','wmode','transparent','menu','false','id','flash','FlashVars','pagina=<?php echo $this->pagina; ?>');</script>	
    </div>
    <h2 title="<?php echo $this->title; ?>" class="<?php echo $this->classe; ?>"><?php echo $this->title; ?></h2>
</div>