<div class="row">

    <div class="span10">
        <h1><?php echo $this->pageTitle; ?></h1>
    </div>

    <div class="span2">
        <a class="btn btn-primary pull-right" href="<?php echo $this->pageUrl; ?>/form"><?php echo $this->novoRegistro; ?></a>
    </div>

</div>

<div class="row">

    <div class="span3">
        <?php echo $this->formFilter; ?>
    </div>

    <div class="span9">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="span6">Título</th>
                    <th class="span2 hidden-phone">Data das Imagens</th>
                    <th class="span1" style="text-align:center;">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->lista->getCurrentItemCount() > 0) : ?>
                    <?php foreach ($this->lista as $dados): ?>
                        <?php $muted = (!$dados->ativo) ? 'muted' : ''; ?>
                        <tr class="<?php echo $muted; ?>">
                            <td class=""><?php echo $this->strLimiter($dados->titulo, 90) ?></td>
                            <td class="hidden-phone"><?php echo $dados->fmt_data(); ?></td>
                            <td style="text-align:center;">
                                <div class="btn-group" style="text-align:left;">
                                    <a class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-white icon-cog"></i>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <?php $label = ($dados->ativo > 0 ? 'desa' : 'a') . 'tivar'; ?>
                                        <li>
                                            <a title="Editar" href="<?php echo $this->pageUrl; ?>/form/id/<?php echo $dados->id; ?>">
                                                <i class="icon-edit"></i> Editar
                                            </a>
                                        </li>
                                        <li>
                                            <a data-target="#modal_status" data-remote="" data-toggle="modal" class="link-status" rel="Tem certeza que deseja <?php echo $label; ?> essa galeria?" title="<?php echo ucfirst($label); ?>" href="<?php echo $this->pageUrl; ?>/ativar-desativar/id/<?php echo $dados->id; ?>">
                                                <i class="icon-thumbs-<?php echo $dados->ativo > 0 ? 'down' : 'up'; ?>"></i> <?php echo ucfirst($label); ?>
                                            </a>
                                        </li>
                                        <li>
                                            <a data-target="#modal_excluir" data-remote="" data-toggle="modal" class="link-excluir" title="Excluir" href="<?php echo $this->pageUrl; ?>/excluir/id/<?php echo $dados->id; ?>">
                                                <i class="icon-trash"></i> Excluir
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="6" align="center">Nenhuma galeria encontrada.</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->lista, 'Sliding', array('admin/paginacao.phtml', 'magic'), array('filtros' => $this->filtros)); ?>
    </div>
</div>

<div id="modal_status" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Confirmação</h3>
    </div>
    <div class="modal-body">
        <p></p>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0);" id="btn-status-confirmacao" class="btn btn-primary">Sim</a>
        <a href="javascript:void(0);" class="btn" data-dismiss="modal">Não</a>
    </div>
</div>

<div id="modal_excluir" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Confirmação</h3>
    </div>
    <div class="modal-body">
        <p>Tem certeza que deseja excluir essa galeria de fotos?</p>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0);" id="btn-excluir-confirmacao" class="btn btn-primary">Sim</a>
        <a href="javascript:void(0);" class="btn" data-dismiss="modal">Não</a>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        $('#limpar').click(function() {
            $('#Galerias_Form_Filtros select option').removeAttr('selected');
            $('#Galerias_Form_Filtros input:text').val('');
            $('#Galerias_Form_Filtros').submit();
        });

        $('#Galerias_Form_Filtros').submit(function() {
            $('#Galerias_Form_Filtros #pagina').val('');
        });

        $('.link-status').click(function(){
            $('#btn-status-confirmacao').attr('href', this.href);
            $('#modal_status .modal-body p').text(this.rel);
        });
        $('.link-excluir').click(function(){
            $('#btn-excluir-confirmacao').attr('href', this.href);
//            $('#modal_excluir .modal-body p').text(this.rel);
        });
    });
</script>
