<div class="row">

    <div class="span10">
        <h1><?php echo $this->pageTitle; ?></h1>
    </div>

    <div class="span2">
        <a class="btn btn-primary pull-right" href="<?php echo $this->pageUrl; ?>/form">Nova lista</a>
    </div>

</div>

<div class="row">

    <div class="span3">
        <?php echo $this->formFilter; ?>
    </div>

    <div class="span9">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="span2">Nome</th>
                    <th class="span2 hidden-phone">Data de abertura</th>
                    <th class="span2 hidden-phone">Data de fechamento</th>
                    <th class="span2 hidden-phone">Cargo</th>
                    <th class="span1" style="text-align:center;">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->lista->getCurrentItemCount() > 0) : ?>
                    <?php foreach ($this->lista as $dados): ?>
                        <?php $muted = (!$dados->isVigente()) ? 'muted' : ''; ?>
                        <tr>
                            <td class="<?php echo ($muted) ?>"><?php echo $dados->nome ?></td>
                            <td class="hidden-phone <?php echo ($muted) ?>"><?php echo $dados->fmt_data_abertura() ?></td>
                            <td class="hidden-phone <?php echo ($muted) ?>"><?php echo $dados->fmt_data_fechamento() ?></td>
                            <td class="hidden-phone <?php echo ($muted) ?>"><?php echo $dados->fmt_area_cargo() ?></td>
                            <td style="text-align:center;">
                                <div class="btn-group" style="text-align:left;">
                                    <a class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-white icon-cog"></i>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a title="Editar" href="<?php echo $this->pageUrl; ?>/form/id/<?php echo $dados->id; ?>">
                                                <i class="icon-edit"></i>
                                                Editar
                                            </a>
                                        </li>
                                        <li>
                                            <a data-target="#modal_excluir" data-remote="" data-toggle="modal" class="link-excluir" title="Excluir" href="<?php echo $this->pageUrl; ?>/excluir/id/<?php echo $dados->id; ?>">
                                                <i class="icon-trash"></i>
                                                Excluir
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5" align="center">Nenhuma lista encontrada.</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->lista, 'Sliding', array('admin/paginacao.phtml', 'magic'), array('filtros' => $this->filtros)); ?>
    </div>

</div>
<div id="modal_excluir" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Confirmação</h3>
    </div>
    <div class="modal-body">
        <p>Tem certeza que deseja excluir essa lista?</p>
    </div>
    <div class="modal-footer">
        <a href="javascript:void(0);" id="btn-excluir-confirmacao" class="btn btn-primary">Sim</a>
        <a href="javascript:void(0);" class="btn" data-dismiss="modal">Não</a>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        <?php if (!IS_MOBILE) : ?>
            $('#data').setMask({autoTab: false}).datepicker();
        <?php endif; ?>

        $('#limpar').click(function() {
            $('#Curriculos_Form_FiltroListas select option').removeAttr('selected');
            $('#Curriculos_Form_FiltroListas input:text').val('');
            $('#Curriculos_Form_FiltroListas').submit();
        });

        $('#Curriculos_Form_FiltroListas').submit(function() {
            $('#Curriculos_Form_FiltroListas #pagina').val('');
        });

        $('.link-excluir').click(function(){
            $('#btn-excluir-confirmacao').attr('href', this.href);
        });
    });
</script>
