<?php
if ($this->pageCount > 1) {
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $partes = array($request->getModuleName(), $request->getControllerName());
    $actionName = $request->getActionName();
    if ($actionName && $actionName != 'index') {
        $partes[] = $actionName;
    }
    $url = implode('/', $partes);
    // A informação do número da página virá do paginador e será adicionada no final da query string
    unset($this->filtros['pagina']);
    // Separa somente os parâmetros que possuem valor (para não remontar a url com parâmetros desnecessários)
    $filtros = array();
    foreach ($this->filtros as $k => $v) {
        if ($v) {
            $filtros[$k] = $v;
        }
    }
    // Remonta a query string com todos os parâmetros que possuem valor
    $query_string = array();
    foreach ($filtros as $k => $v) {
        $query_string[] = "$k=$v";
    }
    $prms = implode('&', $query_string);
    // Define o separador a ser utilizado para agregar o parâmetro correspondente à página no final da url
    if ($prms) {
        $url .= '?' . $prms;
        $sep = '&';
    } else {
        $sep = '?';
    }
    ?>
    <div class="pagination">
        <ul>
            <?php if ($this->first != $this->current) { ?>
                <li>
                    <a title="Primeira" href='<?php echo $url . $sep . 'pagina=' . $this->first; ?>'>&lt;&lt;</a>
                </li>
                <li>
                    <a title="Anterior" href='<?php echo $url . $sep . 'pagina=' . $this->previous; ?>'>&lt;</a>
                </li>
            <?php } else { ?>
                <li class="active">
                    <a title="Primeira" href='<?php echo $url . $sep . 'pagina=' . $this->first; ?>'>&lt;&lt;</a>
                </li>
                <li class="active">
                    <a title="Anterior" href='<?php echo $url . $sep . 'pagina=' . $this->previous; ?>'>&lt;</a>
                </li>
            <?php } ?>

            <?php foreach ($this->pagesInRange as $page) { ?>
                <?php if ($page == $this->current) { ?>
                    <li class="active">
                        <a href='<?php echo $url . $sep . 'pagina=' . $page; ?>'><?php echo $page; ?></a>
                    </li>
                <?php } else { ?>
                    <li>
                        <a href='<?php echo $url . $sep . 'pagina=' . $page; ?>'><?php echo $page; ?></a>
                    </li>
                <?php } ?>

            <?php } ?>

            <?php if ($this->last != $this->current) { ?>
                <li>
                    <a title="Próxima" href='<?php echo $url . $sep . 'pagina=' . $this->next; ?>'>&gt;</a>
                </li>
                <li>
                    <a title="Última" href='<?php echo $url . $sep . 'pagina=' . $this->last; ?>'>&gt;&gt;</a>
                </li>
            <?php } else { ?>
                <li class="active">
                    <a title="Próxima" href='<?php echo $url . $sep . 'pagina=' . $this->next; ?>'>&gt;</a>
                </li>
                <li class="active">
                    <a title="Última" href='<?php echo $url . $sep . 'pagina=' . $this->last; ?>'>&gt;&gt;</a>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>
