<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
</div>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <?php foreach ($this->container as $page) { ?>
            <?php
            if (!$page->isVisible() || !$this->navigation()->accept($page)) {
                continue;
            }
            $hasVisibleChildren = false;
            foreach ($page->getPages() as $subPage) {
                if ($subPage->isVisible() && $this->navigation()->accept($subPage)) {
                    $hasVisibleChildren = true;
                }
            }
            ?>
            <?php if (!$hasVisibleChildren) { ?>
                <?php if ($page->getHref()) { ?>
                    <li <?php //if ($page->isActive()) echo 'class="active"' ?>>
                        <a class="nav-header" href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a>
                    </li>
                <?php } ?>    
            <?php } else { ?>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->translate($page->getLabel()) ?><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <?php foreach ($page->getPages() as $child) { ?>
                            <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                            <li>
                                <a href="<?php echo $child->getHref() ?>"><?php echo $this->translate($child->getLabel()) ?></a>
                            </li>
                        <?php } ?>
                    </ul>
                </li>   
            <?php } ?>
        <?php } ?>
    </ul>
</div>
