<?php

$default_messages = is_array($this->default_messages) ? implode('<br />', $this->default_messages) : null;
$success_messages = is_array($this->success_messages) ? implode('<br />', $this->success_messages) : null;
$error_messages = is_array($this->error_messages) ? implode('<br />', $this->error_messages) : null;
$info_messages = is_array($this->info_messages) ? implode('<br />', $this->info_messages) : null;

$closeButton = '<button type="button" class="close" data-dismiss="alert">&times;</button>';

if ($default_messages) {
    echo '<div class="alert">', $closeButton, $default_messages, '</div>';
}

if ($success_messages) {
    echo '<div class="alert alert-success">', $closeButton, $success_messages, '</div>';
}

if ($error_messages) {
    echo '<div class="alert alert-danger">', $closeButton, $error_messages, '</div>';
}

if ($info_messages) {
    echo '<div class="alert alert-info">', $closeButton, $info_messages, '</div>';
}
