<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
        <base href="<?php echo WWWROOT ?>" />
        <meta name="environment" content="<?php echo APPLICATION_ENV ?>" />
        <link href="bootstrap/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
        <script type="text/javascript" src="js/jquery.meio.mask.min.js"></script>
        <script type="text/javascript" src="js/jquery.magicform.js"></script>
        <style>
            fieldset {
                border: 3px #E0E0E0 dotted;
            }
        </style>
    </head>
    <body>

        <?php echo $this->form ?>

        <script type="text/javascript">
            $(function() {
                
                $('form').magicform({
                    //onOkForwardTo : '<?= WWWROOT ?>curriculos/editar/form'
                });
                
            });

            <?php echo $this->partial('_form.js'); ?>
                
            
        </script>

    </body>

</html>
