<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?= $this->headTitle('Shift [dev]')->setSeparator(' - ')->setAutoEscape(false) ?>
        <link href="<?= BOOTSTRAP_ASSETS ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?= BOOTSTRAP_ASSETS ?>/css/bootstrap-theme.min.css" rel="stylesheet">
        <link href="<?= APPLICATION_ASSETS ?>/css/estilos.css" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div id="wrap">
            <div class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <?= $this->navigation('dev.navigation')->menu()->setUlClass('nav navbar-nav') ?>
                </div>
            </div>
            <div class="container">
                <?//= $this->flash('ink.partial.flash') ?>
                <?= $this->content ?>
            </div>
        </div>
        <div id="footer">
            <div class="container">
                <p class="text-muted">
                    Shift <?='[' . number_format(memory_get_usage(true) / 1024 / 1024, 2) . ' Mb]'?>
                </p>
            </div>
        </div>
        <script src="<?= JQUERY_ASSETS ?>/jquery-1.10.2.min.js"></script>
        <script src="<?= BOOTSTRAP_ASSETS ?>/js/bootstrap.min.js"></script>
        <?= $this->inlineScript() ?>
        <?//= $this->highlight() ?>
    </body>
</html>
