<div class="hero-unit">
    <p>Seja bem-vindo!</p>
    <h1><?php echo $this->usuario->nome; ?></h1>
</div>
<div class="row">
    <?php $acl = Zend_Registry::get('acl'); ?>
    <?php $actualRole = Projeto_Controller_Plugin_Acl::getLoggedRole(); ?>

    <?php if($acl->has('usuarios:admin') && $acl->isAllowed($actualRole, 'usuarios:admin')) : ?>
    <div class="span4">
        <h2>Cadastro de usuários</h2>
        <p>Administração dos cadastros e pesquisas de usuários.</p>
        <a href="usuarios/admin" class="btn btn-primary btn-small">Ir para usuários &raquo;</a>
    </div>
    <?php endif;?>

    <?php if($acl->has('noticias:admin') && $acl->isAllowed($actualRole, 'noticias:admin')) : ?>
    <div class="span4">
        <h2>Cadastro de Notícias</h2>
        <p>Administração dos cadastros e pesquisas de notícias.</p>
        <a href="noticias/admin" class="btn btn-primary btn-small">Ir para notícias &raquo;</a>
    </div>
    <?php endif;?>

    <?php if($acl->has('galerias:admin') && $acl->isAllowed($actualRole, 'galerias:admin')) : ?>
    <div class="span4">
        <h2>Cadastro de Galerias</h2>
        <p>Administração dos cadastros e pesquisas de galerias de fotos.</p>
        <a href="galerias/admin" class="btn btn-primary btn-small">Ir para galerias &raquo;</a>
    </div>
    <?php endif;?>

    <?php if($acl->has('curriculos:admin') && $acl->isAllowed($actualRole, 'curriculos:admin')) : ?>
    <div class="span4">
        <h2>Cadastro de Currículos</h2>
        <p>Administração dos cadastros e pesquisas de currículos.</p>
        <a href="curriculos/admin" class="btn btn-primary btn-small">Ir para currículos &raquo;</a>
    </div>
    <?php endif;?>
</div>