<?php if ($this->pageCount > 1): ?>
<?php $request = Zend_Controller_Front::getInstance()->getRequest(); ?>
<?php $url = $request->getModuleName() . '/' . $request->getControllerName() . '/' . $request->getActionName(); ?>
<tfoot>
    <tr>
    	<td colspan="10">
    	    <div class="paginacao">
    		<span class="txt_paginacao" style="margin-top:3px;">Página <?php echo $this->current; ?> de <?php echo $this->pageCount; ?></span>

		<?php if($this->first != $this->current) : ?>
    		<a title="Primeira" id="paginacao_primeira" href='<?php echo $url . '/pagina/' . $this->first; ?>'>Primeira</a>
    		<a title="Anterior" id="paginacao_anterior" href="<?php echo $url . '/pagina/' . $this->previous; ?>">Anterior</a>
		<?php else : ?>
    		<a title="Primeira" id="paginacao_primeira" href="javascript:void(0);">Primeira</a>
    		<a title="Anterior" id="paginacao_anterior" href="javascript:void(0);">Anterior</a>
		<?php endif; ?>

		<?php foreach ($this->pagesInRange as $page): ?>
		    <?php if ($page != $this->current): ?>
		<span class="numero_paginacao">
		    <a href='<?php echo $url . "/pagina/" . $page; ?>'><strong><?php echo $page; ?></strong></a>
		</span>
		    <?php else: ?>
		<span class="numero_paginacao">
		    <a class="paginacao_numeros" id="paginacao_numero_1" style="border: none"><strong><?php echo $page; ?></strong></a>
		</span>
		    <?php endif; ?>
		<?php endforeach; ?>

		<?php if($this->last != $this->current) : ?>
		<a title="Próxima" id="paginacao_proxima" href="<?php echo $url; ?>/pagina/<?php echo $this->next; ?>">Próxima</a>
		<a title="Última" id="paginacao_ultima"  href='<?php echo $url . '/pagina/' . $this->last; ?>'>Última</a>
		<?php else : ?>
		<a title="Próxima" id="paginacao_proxima" href="javascript:void(0);">Próxima</a>
		<a title="Última" id="paginacao_ultima" href="javascript:void(0);">Última</a>
		<?php endif; ?>
	    </div>
	</td>
    </tr>
</tfoot>
<?php endif; ?>