<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?php echo WWWROOT ?>" />  
        <?php echo $this->headTitle() ?>
        <meta charset="iso-8859-1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="<?php APPNAME; ?>">
        <?php echo $this->headMeta() ?>
        <?php echo $this->headStyle() ?>
        <script type="text/javascript">
            var WWWROOT = '<?php echo WWWROOT ?>';
        </script>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->inlineScript() ?>
        
        <!-- Bootstrap core CSS -->
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <link href="css/estilo.css" rel="stylesheet">
        
        <script src="js/jquery-1.11.1.min.js" type="text/javascript"></script>
        <script src="js/jquery.magicform.js" type="text/javascript"></script>
        <script src="bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
            <?php
            echo $this->flashMessage();
            echo $this->layout()->content;
            ?>


    </body>
</html>
