<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?php echo WWWROOT ?>" />  
        <?php echo $this->headTitle() ?>
        <meta charset="iso-8859-1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="<?php APPNAME; ?>">
        <?php echo $this->headMeta() ?>
        <?php echo $this->headStyle() ?>
        <script type="text/javascript">
            var WWWROOT = '<?php echo WWWROOT ?>';
        </script>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->inlineScript() ?>

        <!-- Bootstrap core CSS -->
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <link href="css/estilo.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="blog-masthead">
            <div class="container">
                <nav class="blog-nav">
                    <a class="blog-nav-item active" href="#">Home</a>
                    <a class="blog-nav-item" href="#">New features</a>
                    <a class="blog-nav-item" href="#">Press</a>
                    <a class="blog-nav-item" href="#">New hires</a>
                    <a class="blog-nav-item" href="#">About</a>
                </nav>
            </div>
        </div>

        <div class="container" style="background-color: white">
            <div class="divLogo">
                <span><img src="img/logo.png" alt=""/></span>
            </div>
            <div class="blog-header">
                <h1 class="blog-title">LISTO Life Support</h1>
                <p class="lead blog-description">Treinamento pessoal · Medicina e Saúde</p>
            </div>
            <?php
            echo $this->flashMessage();
            echo $this->layout()->content;
            ?>
        </div><!-- /.container -->

        <div class="blog-footer">
            <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            <p>
                <a href="#">Back to top</a>
            </p>
        </div>


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->

    </body>
</html>
