<h1><?php echo $this->pageTitle; ?></h1>

<?php echo $this->form ?>

<script type="text/javascript">
    $(function() {
        $('form').magicform({
            onOkForwardTo : '<?php echo $this->backUrl; ?>'
        });
        
<?php if (!IS_MOBILE) { ?>
            $("#pontuacao").setMask({mask : '9999', autoTab: false});
<?php } ?>
            
    });
    
<?php echo $this->partial('_form.js'); ?>

</script>
