<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="iso-8859-1">
        <base href="<?php echo WWWROOT ?>" />
        <?php echo $this->headTitle() ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Magic Web Design">
        <?php echo $this->headMeta() ?>
        <?php
        // -------------------------------------------------------------------------------------------------------------
        // Ícone
        // -------------------------------------------------------------------------------------------------------------
        ?>
        <link rel="shortcut icon" href="" />
        <?php
        // -------------------------------------------------------------------------------------------------------------
        // CSS
        // -------------------------------------------------------------------------------------------------------------
        ?>
        <link href="css/jqueryui/jquery-ui-1.8.14.custom.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
        <link href="css/admin.css" rel="stylesheet">
        <?php echo $this->headStyle() ?>
        <?php
        // -------------------------------------------------------------------------------------------------------------
        // Javascript
        // -------------------------------------------------------------------------------------------------------------
        ?>
        <script type="text/javascript">
            var WWWROOT = '<?php echo WWWROOT ?>';
        </script>
        <!-- IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="js/html5.js"></script>
        <![endif]-->
        <script src="js/jquery-1.7.1.min.js"></script>
        <script src="bootstrap/js/bootstrap.js"></script>
        <script type="text/javascript" src="js/jquery-ui-1.8.14.custom.min.js"></script>
        <script type="text/javascript" src="js/jquery.ui.datepicker-pt-BR.js"></script>
        <script type="text/javascript" src="js/jquery.meio.mask.min.js"></script>
        <script type="text/javascript" src="js/jquery.magicform.js"></script>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->inlineScript() ?>
    </head>

    <body>

        <div class="row">

            <div class="span3">
                <?php echo $this->formFilter ?>
            </div>

            <div class="span9">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th><input id="c_all" type="checkbox" /></th>
                            <th>Nome</th>
                            <th class="hidden-phone">Cidade</th>
                            <th class="hidden-phone">Cargo</th>
                            <th>Pts</th>
                            <th class="hidden-phone">Atualização</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($this->lista && $this->lista->getCurrentItemCount() > 0) : ?>
                            <?php foreach ($this->lista as $dados): ?>
                                <?php $muted = (!$dados->ativo) ? 'muted' : '' ?>
                                <tr>
                                    <td><input id="c_<?php echo $dados->id ?>" name="sel" type="checkbox" /></td>
                                    <td class="<?php echo $muted; ?>"><?php echo $dados->nome ?></td>
                                    <td class="hidden-phone <?php echo $muted; ?>"><?php echo $dados->fmt_cidade() ?></td>
                                    <td class="hidden-phone <?php echo $muted; ?>"><?php echo $dados->getCargos() ?></td>
                                    <td class="<?php echo $muted; ?>" style="text-align: right"><?php echo $dados->pontuacao ?></td>
                                    <td class="hidden-phone <?php echo $muted; ?>"><?php echo $dados->fmt_dh_atualizacao() ?></td>
                                </tr>
                            <?php endforeach ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="6" align="center">Nenhum currículo encontrado.</td>
                            </tr>
                        <?php endif ?>
                    </tbody>
                </table>
                <?php echo $this->lista ? $this->paginationControl($this->lista, 'Sliding', array('admin/paginacao.phtml', 'magic'), array('filtros' => $this->filtros)) : null; ?>
            </div>

        </div>
        
        <div class="row">
            <div class="span12">
                <button name="btn_adicionar_curriculos" id="btn_adicionar_curriculos" type="button" class="btn btn-primary">Adicionar curriculos selecionados</button>
            </div>
        </div>

        <script type="text/javascript">
            $(function() {

                <?php if (!IS_MOBILE) { ?>
                    $('#data_atualizacao').setMask({mask : '99/99/9999', autoTab: false}).datepicker();
                <?php } ?>

                $('#limpar').click(function() {
                    $('#Curriculos_Form_Filtros select option').removeAttr('selected');
                    $('#Curriculos_Form_Filtros input:text').val('');
                    $('#Curriculos_Form_Filtros').submit();
                });
                $('#Curriculos_Form_Filtros').submit(function() {
                    $('#Curriculos_Form_Filtros #pagina').val('');
                });

                $('#area_id').change(function() {
                    var area_id = $(this).val();
                    var comboCargo = $('#cargo_id');
                    var url = '<?php echo WWWROOT ?>curriculos/admin-cargos/lista-combo-cargos/area/' + area_id;
                    comboCargo.empty();
                    if (area_id) {
                        comboCargo.append('<option value="">Carregando...</option>');
                        $.getJSON(url, function(data) {
                            comboCargo.empty();
                            $.each(data, function(key, val) {
                                comboCargo.append('<option value="' + val.id + '">' + val.nome + '</option>');
                            });
                        });
                    } else {
                        comboCargo.append('<option value="">Todos</option>');
                    }
                });

                $('#estado_id').change(function() {
                    var estado_id = $(this).val();
                    var comboCidade = $('#cidade_id');
                    var url = '<?php echo WWWROOT ?>geo/consulta/lista-combo-cidades/uf/' + estado_id;
                    comboCidade.empty();
                    if (estado_id) {
                        comboCidade.append('<option value="">Carregando...</option>');
                        $.getJSON(url, function(data) {
                            comboCidade.empty();
                            $.each(data, function(key, val) {
                                comboCidade.append('<option value="' + val.id + '">' + val.nome + '</option>');
                            });
                        });
                    } else {
                        comboCidade.append('<option value="">Todas</option>');
                    }
                });

                $('#c_all').change(function() {
                    var checked = $(this).attr('checked') ? true : false;
                    $('input:checkbox').attr('checked', checked);
                });

                $('#btn_adicionar_curriculos').live('click', function() {
                    parent.lista_pesquisa_curriculos = '';
                    $('input:checked[name=sel]').each(function() {
                        //alert($(this).attr('id'));
                        var id = $(this).attr('id').substr(2);
                        parent.lista_pesquisa_curriculos += ' ' + id;
                    });
                    parent.adicionaCurriculosSelecionados();
                });

            });
   
        </script>

    </body>
    
</html>
