<h1>Currículos</h1>
<?= $this->form ?>

<? if ($this->curriculos) { ?>

    <? foreach ($this->curriculos as $curriculo) { ?>

        <p><?= $curriculo->id ?> - <?= $curriculo->nome ?> - <?= $curriculo->cidade ?> - <?= $curriculo->estado ?> - <?= $curriculo->pontuacao ?> - <?= $curriculo->fmt_dh_atualizacao() ?></p>
        

    <? } ?>

<? } ?>

<script type="text/javascript">
    $(function() {
        $('form#pesquisar_curriculos').submit(function() {
            $('form#pesquisar_curriculos #pagina').val('1');
        });
    });
</script>




<? return; ?>





<div class="conteudo">
    <div class="agrupa_form2">
        <p class="tit_tela1"><strong class="cor2"><?php echo $this->pageTitle; ?></strong> - Listagem</p>
        <a class="bt" href="<?php echo $this->pageUrl; ?>editar/form/">+ Cadastrar</a>

        <a class="bt_filtro" >Filtro</a>
        <?php echo $this->form_filtros; ?>

        <table cellspacing="0" cellpadding="0" border="0" class="table tabela" id="tabela">
            <thead>
                <tr>
                    <th align="center" style="width:30%;" class="colunas unsort">Nome</th>
                    <th align="center" style="width:20%;" class="colunas unsort">CPF</th>
                    <th align="center" style="width:20%;" class="colunas unsort">E-mail</th>
                    <th align="center" style="width:10%;">Ativo</th>
                    <th align="center" style="width:20%;text-align:center;" colspan="2">Ações</th>
                </tr>
            </thead>
            <?php echo $this->paginationControl($this->lista, 'Sliding', 'common/paginacao.phtml'); ?>
            <tbody>
                <?php if ($this->lista instanceof Zend_Paginator && $this->lista->getCurrentItemCount() > 0) : ?>
                    <?php foreach ($this->lista as $dados): ?>
                        <tr>
                            <td><?php echo $dados->nome; ?></td>
                            <td><?php echo $dados->cpf; ?></td>
                            <td><?php echo $dados->email; ?></td>
                            <td class="acoes" style="text-align:center;">
                                <a title="Alterar" class="bot_link_altera" href="<?php echo $this->pageUrl; ?>editar/form/id/<?php echo $dados->id; ?>">Alterar</a>
                            </td>
                            <td class="acoes" style="text-align:center;">
                                ações
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5" align="center">Nenhum registro encontrado!</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>