<h1><?php echo $this->pageTitle; ?></h1>
<?php echo $this->form ?>
<div id="modal_imagem" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Imagem</h3>
    </div>
    <div class="modal-body">
        <img src="" alt="" title="" style="width:530px;height:400px;" />
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Fechar</a>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        $('form').magicform({
            onOkForwardTo : '<?php echo $this->backUrl; ?>'
        });

        $('#imagem_atual').click(function() {
            $('#modal_imagem .modal-body img').attr('src', this.href);
        });
    });
</script>