
<div class="container-fluid">

    <div class="row form-login">


        <div class="auth-form-header">
            <h1>Sign in</h1>
        </div>

        <div class="col-md-12" >
            <form id="form_login" action="" method="post" class="">
                <br />
                <div class="form-group">
                    <label for="exampleInputEmail1">Login</label>
                    <?php echo $this->form->getElement('login'); ?>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Senha</label>
                    <?php echo $this->form->getElement('senha'); ?>
                </div>
                <br />
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
        <div class="col-md-12" >
            <br />
            <a class="text-muted" href="#" data-toggle="modal" data-target="#myModal">   Esqueci minha senha </a>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Esqueci minha senha</h4>
            </div>
            <form id="form_esqueci_minha_senha" action="<?= WWWROOT ?>login/index/gerar-codigo" method="post">
                <div class="modal-body">

                    <div class="modal-body">                        
                        <label for="email">Por favor, informe seu endereço de e-mail</label>
                        <input id="email" name="email" class="span5" type="text" value="" maxlength="100" />
                        <p>Após clicar em "Confirmar", você receberá um e-mail com instruções e um link para redefinir sua senha.</p>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Confirmar</button>
                </div> 
            </form>
        </div>
    </div>
</div>
