<div class="clearfix hidden-phone hidden-tablet" style="padding-top: 100px"></div>
<div class="row">
    <div class="span4 offset4">
        <h2>Alteração de senha</h2>
        <hr />
        <form action="" method="post">
            <label>Informe uma nova senha</label>
            <input class="span3" type="password" name="senha" id="senha" value="<?= $this->form->getElement('senha')->getValue() ?>" maxlength="100" />
            <label>Redigite a nova senha</label>
            <input class="span3" type="password" name="confirma_senha" id="confirma_senha" value="<?= $this->form->getElement('confirma_senha')->getValue() ?>" maxlength="100" />

            <div class="clearfix" style="padding-top: 10px"></div>

            <button type="submit" class="btn btn-primary">Confirmar</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    //            $('form').magicform();
    $(function() {
        $('#senha').focus();
    });
</script>