<html>
    <head>
        <style type="text/css">
            body {margin: 0; padding: 0; font: 12px Arial; line-height: 18px;}
        </style>
    </head>
    <body>
        <div>
            <p>Olá, <?php echo $this->usuario->nome; ?></p>
            <p></p>
            <p>Para alterar sua senha, acesse <a href="<?php echo WWWROOT; ?>login/index/alterar-senha/codigo/<?php echo $this->codigo; ?>"><?php echo WWWROOT; ?>login/index/alterar-senha/codigo/<?php echo $this->codigo; ?></a>.</p>
        </div>
    </body>
</html>